<a href="https://colab.research.google.com/github/namirachmi08/Text-Similarity/blob/main/Text%20Similarity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Kelas 2025C

Nama Anggota Kelompok:

Namira Rachmi Andini (Nim 25031554153)

Syahira Nanda Raihanna (Nim 25031554199)

# Chapter 7 - Text Similarity

## Cosine Similarity

In [ ]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

# Mengambil teks hasil preprocessing
documents = df["Text_Clean"].fillna("").astype(str)

# Mengubah teks menjadi numerik dengan Count Vectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(documents)

# Menghitung cosine similarity
similarity = cosine_similarity(X)

print(similarity)

[[1.         0.0243975  0.         ... 0.03615508 0.01792443 0.06043979]
 [0.0243975  1.         0.         ... 0.09261982 0.0852757  0.05529674]
 [0.         0.         1.         ... 0.         0.00949105 0.00800077]
 ...
 [0.03615508 0.09261982 0.         ... 1.         0.09234842 0.02458356]
 [0.01792443 0.0852757  0.00949105 ... 0.09234842 1.         0.05687581]
 [0.06043979 0.05529674 0.00800077 ... 0.02458356 0.05687581 1.        ]]


In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer

# Mengambil teks hasil preprocessing
documents = df["Text_Clean"].fillna("").astype(str)

# Mengubah teks menjadi matriks TF-IDF
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(documents)

# Menghitung cosine similarity
similarity = cosine_similarity(X)

print(similarity)

[[1.         0.02114272 0.         ... 0.00878883 0.00601551 0.03179402]
 [0.02114272 1.         0.         ... 0.06578714 0.04970315 0.02587053]
 [0.         0.         1.         ... 0.         0.00836835 0.00699347]
 ...
 [0.00878883 0.06578714 0.         ... 1.         0.04490701 0.00745942]
 [0.00601551 0.04970315 0.00836835 ... 0.04490701 1.         0.02726146]
 [0.03179402 0.02587053 0.00699347 ... 0.00745942 0.02726146 1.        ]]


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from scipy.spatial.distance import pdist

# Mengambil teks hasil preprocessing
documents = df["Text_Clean"].fillna("").astype(str)

# Mengubah teks menjadi binary vector
vectorizer = CountVectorizer(binary=True)
X = vectorizer.fit_transform(documents).toarray()

print(X)

# Menghitung cosine similarity
similarity = 1 - pdist(X, metric='cosine')

print(similarity)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[0.02807173 0.         0.02017425 ... 0.11826248 0.02193172 0.04992872]


## Jaccard

In [ ]:
# JACCARD
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import jaccard_score
from scipy.spatial.distance import pdist

# Mengambil teks hasil preprocessing
documents = df["Text_Clean"].fillna("").astype(str)

# Mengubah teks menjadi binary vector
vectorizer = CountVectorizer(binary=True)
X = vectorizer.fit_transform(documents).toarray()

# Menghitung jarak Jaccard antar semua dokumen
distances = pdist(X, metric='jaccard')

print("Jaccard distance:")
print(distances[:10])

Jaccard distance:
[0.98630137 1.         0.99145299 0.98496241 0.98591549 0.97520661
 0.98076923 0.96946565 0.97687861 1.        ]


In [ ]:
# Similarity dokumen 1 dan 2
Sd1d2 = jaccard_score(X[0], X[1])

# Similarity dokumen 1 dan 3
Sd1d3 = jaccard_score(X[0], X[2])

# Similarity dokumen 2 dan 3
Sd2d3 = jaccard_score(X[1], X[2])

print("Similarity Doc 1 - Doc 2:", Sd1d2)
print("Similarity Doc 1 - Doc 3:", Sd1d3)
print("Similarity Doc 2 - Doc 3:", Sd2d3)

Similarity Doc 1 - Doc 2: 0.0136986301369863
Similarity Doc 1 - Doc 3: 0.0
Similarity Doc 2 - Doc 3: 0.0


In [ ]:
similarity = 1 - distances

print("Jaccard similarity:")
print(similarity[:10])

Jaccard similarity:
[0.01369863 0.         0.00854701 0.01503759 0.01408451 0.02479339
 0.01923077 0.03053435 0.02312139 0.        ]


## Data Real


data: https://drive.google.com/file/d/1AIvJl72GQJnll4Z_AI1MEMVvlJkpke02/view?usp=sharing

In [ ]:
!pip install contractions

import numpy as np
import pandas as pd

from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

import sklearn
import nltk

nltk.download('stopwords')

from IPython.display import display, HTML

data = pd.read_csv("/content/drive/MyDrive/combined_data.csv", header='infer')

print("Total rows : ", len(data))

display(HTML(data.head().to_html()))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


Total rows :  97013


,Unnamed: 0,genre,category,title,year,distribution,description,url,cover_photo
0,0,Romance,Hollywood,Fifty Shades of Grey,2015,BluRay,"Literature student Anastasia Steele's life changes forever when she meets handsome, yet tormented, billionaire Christian Grey.",https://fzmovies.net/movie-Fifty%20Shades%20of%20Grey--hmp4.htm,https://fzmovies.net/imdb_images/%20Fifty.Shades.of.Grey.2015.jpg
1,1,Romance,Hollywood,After,2019,BluRay,"Based on Anna Todd's novel, AFTER follows Tessa (Langford), a dedicated student, dutiful daughter and loyal girlfriend to her high school sweetheart, as she enters her first semester in college. Armed with grand ambitions for her future, her guarded world opens up when she meets the dark and…...<more>",https://fzmovies.net/movie-After%20--hmp4.htm,https://fzmovies.net/imdb_images/After.2019.jpg
2,2,Romance,Hollywood,The Twilight Saga - Breaking Dawn - Part 2,2012,BluRay,"Bella is enjoying her new life and new powers, after the birth of their daughter, Renesmee. Soon, however, their family bliss is threatened again, by a new menace. Vampire Irina believes a child like Renesmee could challenge the power and existence of the Volturi. As Irina rallies the Volturi to destroy this potential threat, Bella and the Cullens - together with any allies they can assemble - are preparing to fight a crucial, ultimate battle, to protect their family. ...<more>",https://fzmovies.net/movie-The%20Twilight%20Saga%20-%20Breaking%20Dawn%20-%20Part%202--hmp4.htm,https://fzmovies.net/imdb_images/The%20Twilight%20Saga:%20Breaking%20Dawn%20-%20Part%202.jpg
3,3,Romance,Hollywood,Alita Battle Angel,2019,BluRay,"Alita is a creation from an age of despair. Found by the mysterious Dr. Ido while trolling for cyborg parts, Alita becomes a lethal, dangerous being. She cannot remember who she is, or where she came from. But to Dr. Ido, the truth is all too clear. She is the one being who can break the cycle of…Tags : cyberpunk | dystopia | cyborg...<more>",https://fzmovies.net/movie-Alita%20Battle%20Angel--hmp4.htm,https://fzmovies.net/imdb_images/Alita.Battle.Angel.2019.jpg
4,4,Romance,Hollywood,Aladdin,2019,BluRay,A kindhearted street urchin and a power-hungry Grand Vizier vie for a magic lamp that has the power to make their deepest wishes come true.,https://fzmovies.net/movie-Aladdin--hmp4.htm,https://fzmovies.net/imdb_images/Aladdin.2019.jpg


In [ ]:
print(data.columns.tolist())

['Unnamed: 0', 'genre', 'category', 'title', 'year', 'distribution', 'description', 'url', 'cover_photo']


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

stemmer = PorterStemmer()
stop_words = set(stopwords.words("english"))

corpus = []

for description in data["description"].fillna("").to_list():
    tokens = description.lower().split()

    # Stemming dan stop-word removal
    tokens = [
        stemmer.stem(token)
        for token in tokens
        if token not in stop_words
    ]

    corpus.append(" ".join(tokens))

print(corpus[0])

literatur student anastasia steele' life chang forev meet handsome, yet tormented, billionair christian grey.


In [ ]:
# Membuat TF-IDF index berdasarkan seluruh corpus
vectorizer = TfidfVectorizer(
    sublinear_tf=True,
    max_features=5000)

vectorizer.fit_transform(corpus)
print("Total features:", vectorizer.get_feature_names_out().shape)
vectorizer.get_feature_names_out()[:1000]

Total features: (5000,)


array(['000', '10', '100', '11', '11th', '12', '13', '13th', '14', '15',
       '16', '17', '18', '18th', '19', '1920', '1930', '1930s', '1940',
       '1941', '1942', '1944', '1945', '1950', '1950s', '1955', '1960',
       '1960s', '1962', '1968', '1969', '1970', '1970s', '1971', '1972',
       '1973', '1974', '1976', '1978', '1980', '1980s', '1984', '1985',
       '1987', '1990', '1999', '19th', '20', '200', '2000', '2002',
       '2003', '2008', '2010', '2011', '2013', '2016', '2017', '2018',
       '2019', '2020', '20th', '21', '21st', '22', '23', '24', '25', '26',
       '30', '300', '40', '400', '4th', '50', '500', '60', '70', '80',
       '90', 'aaron', 'abandon', 'abandoned', 'abbi', 'abduct',
       'abduction', 'abil', 'abl', 'aboard', 'abort', 'about', 'abraham',
       'abroad', 'absolut', 'abus', 'academ', 'academi', 'academy',
       'accept', 'access', 'accid', 'accident', 'acclaim', 'accompani',
       'accomplish', 'accord', 'account', 'accus', 'ace', 'achiev',
       

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

documents_tfidf_features = vectorizer.transform(corpus)

TopK = 10

# Query pencarian film
query = "a young man who discovers a mysterious secret"

# Mengubah query menjadi TF-IDF vector
query_tfidf_features = vectorizer.transform([query])

print("TF-IDF features for query", query_tfidf_features, "\n")

# Menghitung cosine similarity
similarities = cosine_similarity(
    documents_tfidf_features,
    query_tfidf_features
)

# Mengambil 10 dokumen dengan similarity tertinggi
top_indices = similarities[:, 0].argsort()[::-1][:TopK]

titles = []
descriptions = []
similarity_scores = []

for doc_index in top_indices:
    titles.append(data.iloc[doc_index]["title"])
    descriptions.append(
        str(data.iloc[doc_index]["description"]).replace("\n", " ")
    )
    similarity_scores.append(similarities[doc_index, 0])

results = pd.DataFrame({
    "Title": titles,
    "Description": descriptions,
    "Similarities": similarity_scores
})

display(HTML(results.to_html()))

TF-IDF features for query <Compressed Sparse Row sparse matrix of dtype 'float64'
	with 5 stored elements and shape (1, 5000)>
  Coords	Values
  (0, 2763)	0.30097858546349965
  (0, 3001)	0.6868732631713422
  (0, 3930)	0.3881861437012133
  (0, 4893)	0.4558089073009107
  (0, 4986)	0.28136589931310707 



,Title,Description,Similarities
0,Beware The Lake,There are secrets in the waterTags : secret...<more>,0.383353
1,Beware The Lake,There are secrets in the waterTags : secret...<more>,0.383353
2,Beware The Lake,There are secrets in the waterTags : secret...<more>,0.383353
3,The Shack 2017,"A grieving man receives a mysterious, personal invitation to meet with God at a place called ""The Shack.""",0.347141
4,The Shack 2017,"A grieving man receives a mysterious, personal invitation to meet with God at a place called ""The Shack.""",0.347141
5,Nightlight,Five friends play a game in a ''mysterious'' forest with a long history as a beacon for troubled young people contemplating suicide.,0.332022
6,Nightlight,Five friends play a game in a ''mysterious'' forest with a long history as a beacon for troubled young people contemplating suicide.,0.332022
7,Nocturnal,"Laurie, a cynical schoolgirl, builds and nurtures a secret friendship with Pete, an older man who's apparently obsessed with her.\r Tags : teenager | obsession | secret...<more>",0.284896
8,Monsters of California,"Teenager Dallas Edwards, and his derelict friends on a quest for the meaning behind a series of mysterious, paranormal events in Southern California.",0.282989
9,Monsters of California,"Teenager Dallas Edwards, and his derelict friends on a quest for the meaning behind a series of mysterious, paranormal events in Southern California.",0.282989


In [ ]:
# Jaccard
stemmer = PorterStemmer()
stop_words = set(stopwords.words("english"))

corpus = []

for description in data["description"].fillna("").to_list():
    tokens = description.lower().split()

    tokens = [
        stemmer.stem(token)
        for token in tokens
        if token not in stop_words
    ]

    corpus.append(" ".join(tokens))

print(corpus[0])

literatur student anastasia steele' life chang forev meet handsome, yet tormented, billionair christian grey.


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(
    binary=True,
    max_features=5000)

documents_binarized_features = vectorizer.fit_transform(corpus).toarray()

print("Total features:", vectorizer.get_feature_names_out().shape)

vectorizer.get_feature_names_out()[:1000]

Total features: (5000,)


array(['000', '10', '100', '1000', '11', '11th', '12', '13', '13th', '14',
       '15', '16', '17', '18', '18th', '19', '1920', '1930', '1930s',
       '1940', '1941', '1942', '1944', '1945', '1950', '1950s', '1955',
       '1960', '1960s', '1962', '1966', '1968', '1969', '1970', '1970s',
       '1971', '1972', '1973', '1974', '1976', '1978', '1980', '1980s',
       '1984', '1985', '1987', '1990', '1993', '1999', '19th', '20',
       '200', '2000', '2002', '2003', '2008', '2010', '2011', '2013',
       '2016', '2017', '2018', '2019', '2020', '20th', '21', '21st', '22',
       '23', '24', '25', '26', '30', '300', '40', '400', '4th', '50',
       '500', '60', '70', '80', '90', 'aaron', 'abandon', 'abandoned',
       'abbi', 'abduct', 'abduction', 'abil', 'abilities', 'abl',
       'aboard', 'aborigin', 'abort', 'about', 'abraham', 'abroad',
       'absolut', 'abus', 'academ', 'academi', 'academy', 'accept',
       'access', 'accid', 'accident', 'acclaim', 'accompani',
       'accomplish'

In [ ]:
from scipy.spatial.distance import cdist

TopK = 10

query = "a young man who discovers a mysterious secret"

query_binarized_features = vectorizer.transform([query]).toarray()

# Menghitung Jaccard Similarity
similarities = 1 - cdist(
    documents_binarized_features,
    query_binarized_features,
    metric="jaccard"
)

# Mengambil Top 10
top_indices = similarities[:, 0].argsort()[::-1][:TopK]

titles = []
descriptions = []
similarity_scores = []

for doc_index in top_indices:
    titles.append(data.iloc[doc_index]["title"])
    descriptions.append(
        str(data.iloc[doc_index]["description"]).replace("\n", " ")
    )
    similarity_scores.append(similarities[doc_index, 0])

results = pd.DataFrame({
    "Title": titles,
    "Description": descriptions,
    "Similarities": similarity_scores
})

display(HTML(results.to_html()))

,Title,Description,Similarities
0,Some Like It Sexy,A young man fantasizes about fornicating with several women.,0.285714
1,Vaathi,The life of a young man and his struggles against the privatization of education.,0.250000
2,Vaathi,The life of a young man and his struggles against the privatization of education.,0.250000
3,The Unbidden,The Unbidden is a thriller about four women confronted by a mysterious young man who knows a dark secret from their past.,0.230769
4,The Unbidden,The Unbidden is a thriller about four women confronted by a mysterious young man who knows a dark secret from their past.,0.230769
5,The Unbidden,The Unbidden is a thriller about four women confronted by a mysterious young man who knows a dark secret from their past.,0.230769
6,52 Pick Up 1986,A secret fling between a man and his mistress leads to blackmail and murder.,0.222222
7,Ninu Veedani Needanu Nene,Ninu Veedani Needanu Nene is about a young man who gets mired in a dire situation and comes out successfully.,0.222222
8,Kasethan Kadavulada,"A young man, his cousin and a friend stealing money from his stingy stepmother.",0.222222
9,Boyhood,"The life of a young man, Mason, from age 5 to age 18.",0.222222
